### ISSUE TITLE
name 'DefaultCallback' is not defined

### ISSUE THREAD

**Issue by cesarabascal** [PushTheWorld/RaspberryPiADS1299#3]
Hello,
I'm starting into EEG studies.
I'm trying to use your code, but when I run the code, this error appear: name 'DefaultCallback' is not defined
What i'm supposed to do?

Thanks for your help.

**Comment by aj-ptw** [comment]
which code are you running? Did you define a function called `DefaultCallback`?

**Comment by cesarabascal** [comment]
Hello,
I'm using the code from Master repository.
Now I can run the code. The problem was the linux permition.

But now, I'm with another problem. I can't run the cleanup function.

I'm trying to port your code to the Orange Pi Zero.
The code run ok, but when the cleanup it's called, some errors appears.

I'm with another issue, do you have the shield schematic?

Thanks for your help.
